/*
Copyright isaaguilar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	http "net/http"

	infrakubev1 "github.com/galleybytes/infrakube/pkg/apis/infrakube/v1"
	scheme "github.com/galleybytes/infrakube/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type InfrakubeV1Interface interface {
	RESTClient() rest.Interface
	TerraformsGetter
	TofusGetter
}

// InfrakubeV1Client is used to interact with features provided by the infrakube.galleybytes.com group.
type InfrakubeV1Client struct {
	restClient rest.Interface
}

func (c *InfrakubeV1Client) Terraforms(namespace string) TerraformInterface {
	return newTerraforms(c, namespace)
}

func (c *InfrakubeV1Client) Tofus(namespace string) TofuInterface {
	return newTofus(c, namespace)
}

// NewForConfig creates a new InfrakubeV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*InfrakubeV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new InfrakubeV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*InfrakubeV1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &InfrakubeV1Client{client}, nil
}

// NewForConfigOrDie creates a new InfrakubeV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *InfrakubeV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new InfrakubeV1Client for the given RESTClient.
func New(c rest.Interface) *InfrakubeV1Client {
	return &InfrakubeV1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := infrakubev1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *InfrakubeV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
