/*
Copyright isaaguilar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	infrakubev1 "github.com/galleybytes/infrakube/pkg/apis/infrakube/v1"
	scheme "github.com/galleybytes/infrakube/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TofusGetter has a method to return a TofuInterface.
// A group's client should implement this interface.
type TofusGetter interface {
	Tofus(namespace string) TofuInterface
}

// TofuInterface has methods to work with Tofu resources.
type TofuInterface interface {
	Create(ctx context.Context, tofu *infrakubev1.Tofu, opts metav1.CreateOptions) (*infrakubev1.Tofu, error)
	Update(ctx context.Context, tofu *infrakubev1.Tofu, opts metav1.UpdateOptions) (*infrakubev1.Tofu, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tofu *infrakubev1.Tofu, opts metav1.UpdateOptions) (*infrakubev1.Tofu, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*infrakubev1.Tofu, error)
	List(ctx context.Context, opts metav1.ListOptions) (*infrakubev1.TofuList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *infrakubev1.Tofu, err error)
	TofuExpansion
}

// tofus implements TofuInterface
type tofus struct {
	*gentype.ClientWithList[*infrakubev1.Tofu, *infrakubev1.TofuList]
}

// newTofus returns a Tofus
func newTofus(c *InfrakubeV1Client, namespace string) *tofus {
	return &tofus{
		gentype.NewClientWithList[*infrakubev1.Tofu, *infrakubev1.TofuList](
			"tofus",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *infrakubev1.Tofu { return &infrakubev1.Tofu{} },
			func() *infrakubev1.TofuList { return &infrakubev1.TofuList{} },
		),
	}
}
