apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrakube
  namespace: infrakube-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: infrakube
      component: controller
  template:
    metadata:
      labels:
        app: infrakube
        component: controller
    spec:
      serviceAccountName: infrakube
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: infrakube
        image: "ghcr.io/galleybytes/infrakube:latest"
        imagePullPolicy: Always
        args:
        - --zap-log-level=debug
        - --zap-encoder=console
        - --auto-download=true
        - --tf-download-base-url=https://releases.hashicorp.com/terraform
        ports:
        - name: cache
          containerPort: 8082
          protocol: TCP
        env:
        - name: WATCH_NAMESPACE # Leave blank to watch all namespaces
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: infrakube
        resources:
          limits:
            cpu: 50m
            memory: 128M
          requests:
            cpu: 25m
            memory: 128M
        volumeMounts:
        - name: cache
          mountPath: /var/cache/infrakube/terraform
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: infrakube-cache
