name: Build Task Container Image

on:
  pull_request:
    branches:
    - master
    paths:
    - 'task-container-build-tools/**'
  push:
    tags:
    - 'task-*'

jobs:
  task-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get Release Version
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#task-}
        else
          VERSION="0.0.0-$(date +%Y%m%d%H%M%S)"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build & Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TFTASK_TAG: ${{ env.VERSION }}
        TFTASK_PUSH: "true"
      run: |
        cd task-container-build-tools
        uv run python build-tftask.py

    
